### ISSUE TITLE
替换背景图片后管理页面背景全黑

### ISSUE THREAD

**Issue by xwbchn** [Meroser/luci-theme-argon#1]
替换的图片是1080p的jpg文件，我把不需要的bg2-bg4删除了，只保留了bg1.ipg。
效果如下：
![TIM截图20190817193059](https://user-images.githubusercontent.com/31475946/63211119-92a8d680-c125-11e9-87eb-6086aae200bb.png)

**Comment by Meroser** [comment]
出现这种情况是因为管理背景图片是在bg1-4中随机显示，你删除了234，就会出现这样的情况
